# Generated by Django 3.2.4 on 2021-07-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_topic_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='header_image',
            field=models.ImageField(blank=True, default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
